### PR TITLE
[CORS ORIGIN] :lock: Enabling Cross Origin Requests for a RESTful Web…

### LINKED ISSUE #15: Preflighted requests
**Describe the bug**
Access to XMLHttpRequest at 'http://localhost:8081/api/v1/users/authenticate' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status

**To Reproduce**
send a POST request with 'content-type': 'application/json'  require to send OPTION request to determine if the actual request is safe to send.

**Expected behavior**
handle OPTION requests
**Additional context**
please check this article 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

### PR DESCRIPTION
**Pull request by DjihadBengati**
Preflighted requests
Fix #15

### CODE REVIEW

File: src/main/java/org/openemp/api/user/OpenempUserApiApplication.java [hunk 1]
```diff
@@ -17,7 +22,18 @@
...
+	@Bean
+	public WebMvcConfigurer corsConfigurer() {
+		return new WebMvcConfigurer() {
+			@Override
+			public void addCorsMappings(CorsRegistry registry) {
+				registry.addMapping(Constant.AUTH_LOGIN_URL).allowedMethods(HttpMethod.OPTIONS.name(), HttpMethod.POST.name());
+				registry.addMapping(Constant.USER_ENDPOINT).allowedMethods(HttpMethod.OPTIONS.name(), HttpMethod.POST.name());
+			}
+		};
+	}
```
Comment (chinzou) [inline src/main/java/org/openemp/api/user/OpenempUserApiApplication.java]: Is it possible to move this to `WebSecurityConfig`?

Comment (DjihadBengati) [reply src/main/java/org/openemp/api/user/OpenempUserApiApplication.java]: Done !

**Comment by chinzou** [comment]
Thanks @DjihadBengati
